# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'I am Constantin Ruhdorfer, a Ph.D. scholar at the International Max Planck Research School for Intelligent Systems (IMPRS-IS) and the HCI-CS group at the University of Stuttgart, Germany. I work to improve human-AI cooperation by investigating the intersection of Machine Theory of Mind and Multi-Agent Reinforcement Learning.'
url:              https://constantinruhdorfer.github.io/
baseurl:          /

author:
  name:           'Constantin Ruhdorfer'
  url:            https://www.perceptualui.org/people/ruhdorfer/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
